# Generated by Django 5.0.4 on 2024-06-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.CharField(max_length=255)),
                ('translation', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'sentences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
    ]
